import mysql.connector

# MySQL 연결
conn = mysql.connector.connect(
    host="t2rds.cfa60ymesotv.ap-northeast-2.rds.amazonaws.com",
    user="admin",
    password="dltkddn1",
    database="service"
)
cursor = conn.cursor()

# tech_name과 docs_link를 매칭한 딕셔너리
tech_docs = {
    "Jupyter": "https://jupyter.org/documentation",
    "Spyder": "https://docs.spyder-ide.org/",
    "PyCharm": "https://www.jetbrains.com/pycharm/documentation/",
    "VSCode": "https://code.visualstudio.com/docs",
    "Sublime Text": "https://www.sublimetext.com/docs/",
    "Vim": "https://www.vim.org/docs.php",
    "Emacs": "https://www.gnu.org/software/emacs/manual/",
    "CI/CD": "https://www.atlassian.com/continuous-delivery/ci-vs-ci-vs-cd",
    "Machine Learning": "https://scikit-learn.org/stable/user_guide.html",
    "Deep Learning": "https://www.tensorflow.org/learn",
    "Natural Language Processing": "https://www.nltk.org/",
    "Hadoop": "https://hadoop.apache.org/docs/r1.2.1/",
    "Spark": "https://spark.apache.org/docs/latest/",
    "Kafka": "https://kafka.apache.org/documentation/",
    "HBase": "https://hbase.apache.org/book.html",
    "Cassandra": "https://cassandra.apache.org/_/index.html",
    "PostgreSQL": "https://www.postgresql.org/docs/",
    "MySQL": "https://dev.mysql.com/doc/",
    "SQLite": "https://www.sqlite.org/docs.html",
    "MongoDB": "https://docs.mongodb.com/",
    "Redis": "https://redis.io/documentation",
    "Elasticsearch": "https://www.elastic.co/guide/index.html",
    "Solr": "https://solr.apache.org/guide/",
    "Apache Storm": "https://storm.apache.org/releases/current/documentation.html",
    "Flume": "https://flume.apache.org/",
    "Airflow": "https://airflow.apache.org/docs/apache-airflow/stable/",
    "Celery": "https://docs.celeryproject.org/en/stable/",
    "Apache Camel": "https://camel.apache.org/manual/latest/",
    "Kotlin": "https://kotlinlang.org/docs/home.html",
    "Java": "https://docs.oracle.com/en/java/",
    "JavaScript": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference",
    "TypeScript": "https://www.typescriptlang.org/docs/",
    "Swift": "https://developer.apple.com/swift/",
    "Ruby": "https://www.ruby-lang.org/en/documentation/",
    "Go": "https://golang.org/doc/",
    "Rust": "https://doc.rust-lang.org/book/",
    "PHP": "https://www.php.net/manual/en/",
    "SQLAlchemy": "https://docs.sqlalchemy.org/en/14/",
    "JDBC": "https://docs.oracle.com/javase/8/docs/technotes/guides/jdbc/",
    "Selenium": "https://www.selenium.dev/documentation/en/",
    "Cypress": "https://www.cypress.io/docs/",
    "Appium": "https://appium.io/docs/en/about-appium/intro/",
    "Terraform": "https://www.terraform.io/docs",
    "Ansible": "https://docs.ansible.com/ansible/latest/index.html",
    "Docker": "https://docs.docker.com/",
    "Kubernetes": "https://kubernetes.io/docs/",
    "OpenShift": "https://docs.openshift.com/container-platform/latest/",
    "Vagrant": "https://www.vagrantup.com/docs",
    "Git": "https://git-scm.com/doc",
    "GitHub": "https://docs.github.com/en/github",
    "GitLab": "https://docs.gitlab.com/ee/",
    "Bitbucket": "https://confluence.atlassian.com/bitbucket/",
    "Jenkins": "https://www.jenkins.io/doc/",
    "Travis CI": "https://docs.travis-ci.com/",
    "CircleCI": "https://circleci.com/docs/",
    "Puppet": "https://puppet.com/docs/puppet/latest/puppet_index.html",
    "Chef": "https://docs.chef.io/",
    "Nagios": "https://www.nagios.org/documentation/",
    "Prometheus": "https://prometheus.io/docs/",
    "Grafana": "https://grafana.com/docs/",
    "Zabbix": "https://www.zabbix.com/documentation/current/manual",
    "Logstash": "https://www.elastic.co/guide/en/logstash/current/index.html",
    "Fluentd": "https://docs.fluentd.org/",
    "Loggly": "https://www.loggly.com/docs/",
    "Datadog": "https://docs.datadoghq.com/",
    "New Relic": "https://docs.newrelic.com/docs",
    "Sentry": "https://docs.sentry.io/",
    "AppDynamics": "https://docs.appdynamics.com/",
    "GraphQL": "https://spec.graphql.org/",
    "REST API": "https://restfulapi.net/",
    "gRPC": "https://grpc.io/docs/",
    "WebSocket": "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API",
    "Socket.io": "https://socket.io/docs/",
    "Nginx": "https://nginx.org/en/docs/",
    "Apache HTTP Server": "https://httpd.apache.org/docs/",
    "Lighttpd": "https://www.lighttpd.net/docs/",
    "Tomcat": "https://tomcat.apache.org/tomcat-9.0-doc/",
    "Jetty": "https://www.eclipse.org/jetty/documentation/",
    "WildFly": "https://docs.wildfly.org/",
    "Spring Boot": "https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/",
    "Spring MVC": "https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc",
    "Spring Security": "https://docs.spring.io/spring-security/site/docs/current/reference/html5/",
    "Spring Cloud": "https://docs.spring.io/spring-cloud/docs/current/reference/html/",
    "Spring Data": "https://docs.spring.io/spring-data/commons/docs/current/reference/html/",
    "Spring Batch": "https://docs.spring.io/spring-batch/docs/current/reference/html/",
    "Spring Integration": "https://docs.spring.io/spring-integration/docs/current/reference/html/",
    "Node.js": "https://nodejs.org/en/docs/",
    "Express": "https://expressjs.com/en/starter/installing.html",
    "Vue.js": "https://vuejs.org/v2/guide/",
    "React": "https://reactjs.org/docs/getting-started.html",
    "Angular": "https://angular.io/docs",
    "Svelte": "https://svelte.dev/docs",
    "Next.js": "https://nextjs.org/docs",
    "Nuxt.js": "https://nuxtjs.org/docs",
    "Ember.js": "https://guides.emberjs.com/",
    "Django": "https://docs.djangoproject.com/en/stable/",
    "Flask": "https://flask.palletsprojects.com/en/latest/",
    "Ruby on Rails": "https://guides.rubyonrails.org/",
    "Laravel": "https://laravel.com/docs",
    "Spring Framework": "https://docs.spring.io/spring-framework/docs/current/reference/html/",
    "ASP.NET": "https://learn.microsoft.com/en-us/aspnet/core/",
    "Symfony": "https://symfony.com/doc/current/",
    "Meteor": "https://docs.meteor.com/",
    "Hapi": "https://hapi.dev/api/",
    "Golang": "https://golang.org/doc/",
    "C++": "https://en.cppreference.com/w/cpp",
    "C#": "https://learn.microsoft.com/en-us/dotnet/csharp/",
    "C": "https://en.cppreference.com/w/c/language",
    "Python": "https://docs.python.org/3/",
    "Perl": "https://perldoc.perl.org/",
    "CoffeeScript": "https://coffeescript.org/v2/docs/",
    "Shell": "https://www.gnu.org/software/bash/manual/bashref.html",
    "SQL": "https://www.sqltutorial.org/",
    "NoSQL": "https://www.mongodb.com/nosql-explained",
    "MariaDB": "https://mariadb.com/kb/en/documentation/",
    "Agit": "https://agit.ai/",
    "Tableau": "https://www.tableau.com/support",
    "PyTorch": "https://pytorch.org/docs/stable/index.html",
    "TensorFlow": "https://www.tensorflow.org/docs",
    "AWS Athena": "https://docs.aws.amazon.com/athena/",
    "LLM": "https://en.wikipedia.org/wiki/Large_language_model",
    "CSS": "https://developer.mozilla.org/en-US/docs/Web/CSS",
    "Amazon S3": "https://docs.aws.amazon.com/s3/",
    "AWS Redshift": "https://docs.aws.amazon.com/redshift/",
    "Firebase": "https://firebase.google.com/docs",
    "Snowflake": "https://docs.snowflake.com/",
    "Amazon CloudWatch": "https://docs.aws.amazon.com/cloudwatch/",
    "Impala": "https://impala.apache.org/docs/",
    "GitHub Actions" : "https://docs.github.com/ko/actions"
}

# 각 기술에 대해 docs_link 값을 업데이트
for tech, docs_link in tech_docs.items():
    query = """
        UPDATE tech_stack
        SET docs_link = %s
        WHERE tech_name = %s
    """
    cursor.execute(query, (docs_link, tech))
    print(f"Updated docs_link for {tech}")

# 변경 사항 커밋
conn.commit()

# 연결 종료
cursor.close()
conn.close()
